---
- name: PLAY - TEST JINJA2 TEMPLATING
  hosts: elasticsearch_servers

  gather_facts: yes
  gather_timeout: 10

  remote_user: bouldrini
  become: yes

  tasks:
    - name: Check whether /etc/elasticsearch/jvm.options contains min Heap Size Parameter
      lineinfile:
        name: /etc/elasticsearch/jvm.options
        line: '-Xms1975m'
        state: present
      check_mode: yes
      register: conf

    
