---
dependencies: []

galaxy_info:
  author: bouldrini
  description: Java for Linux
  company: "FH Erfurt"
  license: ""
  min_ansible_version: 2.8
  platforms:
    - name: Ubuntu
      versions:
        - xenial
  galaxy_tags:
    - development
    - system
    - java
    - jdk
    - openjdk
