---

# ================================================================================================================
# INSTALLING SYSTEM REQUIREMENTS LIKE REPOSITORIES
# ================================================================================================================

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'






# ================================================================================================================
# ELASTICSEARCH INSTALLATION
# ================================================================================================================

- name: Install Elasticsearch.
  package:
    name: elasticsearch
    state: "{{ elasticsearch_package_state }}"





# ================================================================================================================
# ELASTICSEARCH CONFIGURATION
# ================================================================================================================

# according to documentation: https://www.elastic.co/guide/en/elasticsearch/reference/current/important-settings.html
#..................................................................................................................

- name: Configure Elasticsearch.
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch
    mode: 0666




# ------------------------------------------------------------------------------------------------------------------
# IMPORTANT ELASTICSEARCH CONFIGURATIONS
# ------------------------------------------------------------------------------------------------------------------


# ENSURE HEAP SIZE ADJUSTMENT IDEMPOTENCY
# Ensure /etc/elasticsearch/jvm.options contains default values for heap sizes to ensure idempotency for playbook runs
#..................................................................................................................
- name: Check if /etc/elasticsearch/jvm.options contains default start heap size adjustment
  lineinfile:
    name: /etc/elasticsearch/jvm.options
    line: "-Xms1g"
    state: present
  check_mode: yes
  register: start_heapsize_default

- name: Check if /etc/elasticsearch/jvm.options contains default end heap size adjustment
  lineinfile:
    name: /etc/elasticsearch/jvm.options
    line: "-Xmx1g"
    state: present
  check_mode: yes
  register: end_heapsize_default






# ADJUSTING HEAP SIZE FOR SYSTEMS WITH MORE THAN 52G MEMORY
# Set a limit of 26G to use recommended zero-based compressed oops
# according to documentation:
#     - https://www.elastic.co/guide/en/elasticsearch/reference/current/heap-size.html
#..................................................................................................................
- name: Check if system memory is greater than 52G
  debug: msg="System memory is {{ hostvars[inventory_hostname]['ansible_memory_mb']['real'].total | int }} so setting heapsize to use zero based OOP"
  when: hostvars[inventory_hostname]['ansible_memory_mb']['real'].total | int >= 52000

# ---- start heapsize adjustment for greater systems
- name: Apply heapsize start tuning for systems with greater than 52G memory
  lineinfile:
    path=/etc/elasticsearch/jvm.options
    regexp='^-Xms1g'
    line='-Xms26g'
  when: 
    - hostvars[inventory_hostname]['ansible_memory_mb']['real'].total | int >= 52000
    - start_heapsize_default
  become: true

# ---- end heapsize adjustment for greater systems
- name: Apply heapsize end tuning for systems with greater than 52G memory
  lineinfile:
    path=/etc/elasticsearch/jvm.options
    regexp='^-Xmx1g'
    line='-Xmx26g'
  when: 
    - hostvars[inventory_hostname]['ansible_memory_mb']['real'].total | int >= 52000
    - end_heapsize_default
  become: true
  notify: restart elasticsearch





# ADJUSTING HEAP SIZE FOR SYSTEMS WITH LESS THAN 52G MEMORY
# Set Heap Size to 50% of the memory
# according to documentation: 
#    - https://www.elastic.co/guide/en/elasticsearch/reference/current/heap-size.html
#..................................................................................................................
- name: Check if system memory is less than 52G
  debug: msg="System memory is {{ hostvars[inventory_hostname]['ansible_memory_mb']['real'].total | int }} so setting heapsize to 50%"
  when: hostvars[inventory_hostname]['ansible_memory_mb']['real'].total | int < 52000


# ---- start heapsize adjustment
- name: Update elasticsearch startup with start heap size
  become: true
  ignore_errors: yes
  lineinfile:
    path=/etc/elasticsearch/jvm.options
    regexp='^-Xms1g'
    line='-Xms{{ (hostvars[inventory_hostname]['ansible_memory_mb']['real'].total / 2) | int }}m'
  when: 
    - hostvars[inventory_hostname]['ansible_memory_mb']['real'].total | int < 52000
    - start_heapsize_default
  notify: restart elasticsearch

# ---- end heapsize adjustment
- name: Update elasticsearch startup with end heap size
  become: true
  lineinfile:
    path=/etc/elasticsearch/jvm.options
    regexp='^-Xmx1g'
    line='-Xmx{{ (hostvars[inventory_hostname]['ansible_memory_mb']['real'].total / 2) | int }}m'
  when: 
    - hostvars[inventory_hostname]['ansible_memory_mb']['real'].total|int < 52000
    - end_heapsize_default
  notify: restart elasticsearch






# ------------------------------------------------------------------------------------------------------------------
# ADJUST FILESYSTEM PERMISSIONS
# ------------------------------------------------------------------------------------------------------------------

- name: Change elasticsearchs log folder (/var/log/elasticsearch) permissions to 0644
  file:
    path: /var/log/elasticsearch
    owner: elasticsearch
    group: elasticsearch
    mode: '0775'

- name: Change elasticsearchs etc folder (/etc/elasticsearc)h permissions to 0644
  file:
    path: /etc/elasticsearch
    owner: root
    group: elasticsearch
    mode: '0775'







# ------------------------------------------------------------------------------------------------------------------
# IMPORTANT SYSTEM CONFIGURATIONS
# ------------------------------------------------------------------------------------------------------------------

# ENSURE LIMITS ARE NOT IGNORED AT STARTUP
# according to documentation:
#    -https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-configuration-memory.html
#..................................................................................................................
- name: Ensure pam_limits.so line is uncommented to make processes started by init.d use limits.conf
  replace:
    path: /etc/pam.d/su
    regexp: '# session    required   pam_limits.so'
    replace: 'session    required   pam_limits.so'

- name: Ensure pam_limits.so line is uncommented to make processes started by init.d use limits.conf
  replace:
    path: /etc/pam.d/su
    regexp: '#session    required   pam_limits.so'
    replace: 'session    required   pam_limits.so'





# DISABLE SWAPPING
# according to documentation: 
#    -https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-configuration-memory.html
#..................................................................................................................
- name: Set elasticsearchs default variable MAX_LOCKED_MEMORY to unlimited
  replace:
    path: /etc/default/elasticsearch
    regexp: '#MAX_LOCKED_MEMORY'
    replace: 'MAX_LOCKED_MEMORY'

- name: Update /etc/security/limits.conf to allow soft memlock for elasticsearch (adjustable through group variable custom_elasticsearch_soft_memlock, default unlimited)
  lineinfile:
    path: /etc/security/limits.conf
    line: '* soft memlock {{ elasticsearch_soft_memlock }}'
    create: yes

- name: Update /etc/security/limits.conf to allow hard memlock for elasticsearch (adjustable through group variable custom_elasticsearch_hard_memlock, default unlimited)
  lineinfile:
    path: /etc/security/limits.conf
    line: '* hard memlock {{ elasticsearch_hard_memlock }}'
    create: yes

- name: Update /usr/lib/systemd/system/elasticsearch.service to set vm.swappiness=1 to reduce the kernels tendency to swap
  lineinfile:
    path: /usr/lib/systemd/system/elasticsearch.service
    insertafter: '\[Service\]'
    line: 'LimitMEMLOCK=infinity'
    create: yes
  notify: reload service deamon

- name: Update /etc/sysctl.conf to set vm.swappiness=1 to reduce the kernels tendency to swap
  lineinfile:
    path: /etc/sysctl.conf
    line: 'vm.swappiness=1'
    create: yes






# FILE DESCRIPTORS
# according to documentation:
#   - https://www.elastic.co/guide/en/elasticsearch/reference/current/setting-system-settings.html
#   - https://www.elastic.co/guide/en/elasticsearch/reference/current/file-descriptors.html
#..................................................................................................................
- name: Update /etc/security/limits.conf to allow a huge number of open files for elasticsearch (adjustable through group variable custom_elasticsearch_number_of_open_files, default 65535)
  lineinfile:
    path: /etc/security/limits.conf
    line: '*  -  nofile  {{ elasticsearch_number_of_open_files }}'
    create: yes

- name: Set elasticsearchs default variable MAX_OPEN_FILES to suggested 65535
  replace:
    path: /etc/default/elasticsearch
    regexp: '#MAX_OPEN_FILES'
    replace: 'MAX_OPEN_FILES'






# VIRTUAL MEMORY
# according to documentation:
#    - https://www.elastic.co/guide/en/elasticsearch/reference/current/vm-max-map-count.html
#..................................................................................................................
- name: Update /etc/sysctl.conf to allow a huge number of mmap counts (virtual memory) for elasticsearch (adjustable through group variable custom_elasticsearch_virtual_memory_mmap_counts, default 262144)
  lineinfile:
    path: /etc/sysctl.conf
    line: 'vm.max_map_count={{ elasticsearch_virtual_memory_mmap_counts }}'
    create: yes

- name: Set elasticsearchs default variable MAX_MAP_COUNT to suggested 262144
  replace:
    path: /etc/default/elasticsearch
    regexp: '#MAX_MAP_COUNT'
    replace: 'MAX_MAP_COUNT'




# NUMBER OF THREADS
# according to documentation:
#     - https://www.elastic.co/guide/en/elasticsearch/reference/current/max-number-of-threads.html
#..................................................................................................................
- name: Update /etc/security/limits.conf to allow a huge number of threads for elasticsearch (adjustable through group variable custom_elasticsearch_number_of_threads, default 4096)
  lineinfile:
    path: /etc/security/limits.conf
    line: '* -  nproc {{ elasticsearch_number_of_threads }}'
    create: yes





# DNS Cache Settings
# according to documentation:
#     - https://www.elastic.co/guide/en/elasticsearch/reference/current/networkaddress-cache-ttl.html
#     - https://docs.oracle.com/javase/8/docs/technotes/guides/net/properties.html
#..................................................................................................................
- name: Adjust DNS Cache Settings - Set networkaddress.cache.ttl to given value in /etc/elasticsearch/jvm.optins (adjustable through group variable custom_elasticsearch_dns_cache_ttl, default 60)
  replace:
    path: /etc/elasticsearch/jvm.options
    regexp: '-Des.networkaddress.cache.ttl=60'
    replace: '-Des.networkaddress.cache.ttl={{ elasticsearch_dns_cache_ttl }}'

- name: Adjust DNS Cache Settings - Set networkaddress.cache.negative.ttl to given value in /etc/elasticsearch/jvm.optins (adjustable through group variable custom_elasticsearch_dns_cache_negative_ttl, default 60)
  replace:
    path: /etc/elasticsearch/jvm.options
    regexp: '-Des.networkaddress.cache.negative.ttl=10'
    replace: '-Des.networkaddress.cache.negative.ttl={{ elasticsearch_dns_cache_negative_ttl }}'





# JNA TEMP DIRECTORY NOT MOUNTED WITH noexec
# according to documentation:
#    - https://www.elastic.co/guide/en/elasticsearch/reference/current/executable-jna-tmpdir.html
#..................................................................................................................
- name: Set additional Java Options for JNA temp directory and other options if required (adjustable through group variable custom_elasticsearch_additional_jvm_opts)
  replace:
    path: /etc/default/elasticsearch
    regexp: '#ES_JAVA_OPTS='
    replace: 'ES_JAVA_OPTS={{ elasticsearch_additional_jvm_opts }}'




# ================================================================================================================
# RESTARTING ELASTICSEARCH AFTER CONFIGURATION
# ================================================================================================================

- name: Force a restart if configuration has changed.
  meta: flush_handlers

- name: Start Elasticsearch.
  service:
    name: elasticsearch
    state: "started"
    enabled: "true"

- name: Make sure Elasticsearch is running before proceeding.
  wait_for:
    host: "{{ elasticsearch_network_host }}"
    port: "{{ elasticsearch_http_port }}"
    delay: 3
    timeout: 300
